"""empty message

Revision ID: 12afc18c54c3
Revises: f25dded2dc91
Create Date: 2019-10-10 12:15:33.593609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12afc18c54c3'
down_revision = 'f25dded2dc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'post', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
