"""empty message

Revision ID: 81702075ea76
Revises: 84ede090d75d
Create Date: 2019-10-11 14:23:04.713366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81702075ea76'
down_revision = '84ede090d75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
